import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {useForm, SubmitHandler, FormProvider, Controller} from 'react-hook-form';
import { yupResolver} from '@hookform/resolvers/yup';
import * as yup from 'yup';

import Input from './components/input';
import { TextField } from '@material-ui/core';

interface IFormInputs {
  email: string,
  password: string
}

const scheme: yup.SchemaOf<IFormInputs> = yup.object().shape({
  email: yup.string().email().required(),
  password: yup.string().min(8).max(20).required()
})

// const resolver: Resolver<IFormInputs> = yupResolver(scheme);

const Home: NextPage = () => {
  const methods = useForm<IFormInputs>({ resolver: yupResolver(scheme)})

  const formSubmitHandler: SubmitHandler<IFormInputs> = (data: IFormInputs) => {
    console.log(data)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <FormProvider {...methods}>
          <form onSubmit={methods.handleSubmit(formSubmitHandler)}>
          {/* <Controller name='email' control={methods.control} defaultValue='' render={({field}) => (<TextField {...field} label='email' variant='outlined' error={!!methods.formState.errors.email} helperText={methods.formState.errors.email ? methods.formState.errors.email?.message : ''}/>)} />   
            <br />
            <br />
            <Controller name='password' control={methods.control} defaultValue=''  render={({field}) => (<TextField {...field} label='password' type='password' variant='outlined' error={!!methods.formState.errors.password} helperText={methods.formState.errors.password ? methods.formState.errors.password?.message : ''}/>)} />   
            <br/>
            <br/> */}
            <Input />
            <input type='submit' />
          </form>
        </FormProvider>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
